version: "3"

services:
  server:
    image: motion-server:latest
    expose:
      - 8080
    environment:
      - MOTION_PROD=false # change to true

  web-client:
    image: motion-web-client:latest
    expose:
      - 8080
    environment:
      - NGINX_PORT=8080

  nginx:
    image: nginx:1.25-alpine3.18-slim
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
    environment:
      - HOST_SERVER=http://server:8080
      - HOST_WEB_CLIENT=http://web-client:8080
    restart: always
    depends_on:
      - server
      - web-client
